/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lfrexldtbsnhjmwslfjq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcmV4bGR0YnNuaGptd3NsZmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3NjUyNzcsImV4cCI6MjA4MTM0MTI3N30.pKz-99ZCFQRMnZhN-fCNzxB3ud5nR2nurTU0niw0mo0"